# Numpy

## Numpy数据类型

In [1]:
import numpy as np

A = [[2,1],[3,4]]

Arr = np.array(A)
print(Arr*Arr)
print(Arr.dot(Arr))
Mtr = np.matrix(A)
print(Mtr*Mtr)

[[ 4  1]
 [ 9 16]]
[[ 7  6]
 [18 19]]
[[ 7  6]
 [18 19]]


In [85]:
#help(np.argmax)

In [19]:
# 0001 1
# 0010 2
# 0000 0 = 1&2
# 0011 3 = 1|2
print(1&2)
print(1|2)

0
3


In [17]:
X = np.array([1,2,3,4,5,6,1,7,8,9,9,0])
m = X.mean()
X[X<m]=0
# print(X>3,'\n',X<7)
print(X>3)
print(~(X>3))
# print((X>3) & (X<7))
# print((X>3) | (X<7))

# I = np.where(X==1)
# print(X[I])
# print(X==1)
# print(X[X==1])

[False False False False  True  True False  True  True  True  True False]
[ True  True  True  True False False  True False False False False  True]


In [28]:
X = np.arange(15).reshape((3,5))
print(X)
print(X.sum(axis=1))
# broadcast
print(X/X.sum(axis=1).reshape(-1,1))
print(X/X.sum(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[10 35 60]
[[ 0.          0.1         0.2         0.3         0.4       ]
 [ 0.14285714  0.17142857  0.2         0.22857143  0.25714286]
 [ 0.16666667  0.18333333  0.2         0.21666667  0.23333333]]
[[ 0.          0.05555556  0.0952381   0.125       0.14814815]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.66666667  0.61111111  0.57142857  0.54166667  0.51851852]]
